[package]
name = "outbound-delivery-worker"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "outbound-delivery-worker"
path = "src/main.rs"

[dependencies]
notification = { workspace = true }
observability = { workspace = true }

anyhow = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../../packages/workspace-hack" }

[lints]
workspace = true
