#ENC[AES256_GCM,data:OExpDCIvrpFxYRAVuj7vekR7hCatimfCf0lL4CRCjFEsJ8fDGW5zfY/O,iv:7cLxtuKh1nZPGORRPGxM54rJhn3QDkNBT+bMtKMfShc=,tag:7OVuXSYXz6IXUv3D0zVshA==,type:comment]
#
#ENC[AES256_GCM,data:3xjY78NTUe+pXPnJBZAxoNV6m0TWrbRLjaACWExwvhOFGyOZleUz4J/qmguR1uM4xtup0A==,iv:DMHcgM+UAHRXsVLK7HdaPi1ERfPMSw7bT5eObUCwA1g=,tag:Fk4ULx/N4AFxEsIGzWXV0Q==,type:comment]
#ENC[AES256_GCM,data:/wHFnCutF21AnPYJA8dLL24oOgM5wo8bcnBCiM/52/8YrdxOZgZjru21Ocv53NtGvjy63XiIdgpDgLrczpY6Dl9QLfUA2v1vGgbpSZSlCBMub+BRm7oIIEGvwuGA,iv:oGDzRScQFqEjhZZEswDnuynJ6JML9k5sLWtIZ57mIo4=,tag:3KsmI1fJttUMiPROyqz2nA==,type:comment]
#
#ENC[AES256_GCM,data:LzS1qnCY6PFYQowIoheoVIwOv9ZSQAo+cBm1AFPeTFVWU6aEH1jdsT0gWGgQXCd3evGoaM9PiRnOJ3hk3IENo+o=,iv:hJ5zRuLLUAhVu0mbB8fn/GirDMInhIyIQadb/A9lu50=,tag:WEyrAPJSsobU2R3TWgv+rw==,type:comment]
apiVersion: ENC[AES256_GCM,data:Nhs=,iv:+/Odk8t6vXfhVteqOHgv/fBE0gjtoOfsk7LMEkJbmG4=,tag:zbjtMkPaBN6iOQNUkybqkw==,type:str]
kind: ENC[AES256_GCM,data:PjI8kUO0,iv:BW9nDRpKQlL01f2rMLdGLVSgHBFGH+BXgnAacgStRT4=,tag:UqiBh+HZ/4PNAtyxQsfo0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FO9XyAAxTkgsaXxjlC+RbSg+5h9J/SpX,iv:eYnawFRQYX7G1NLyQoQ72dgKf66VR33SJqtxC25dPZ4=,tag:iRITtVrw+TonxM/6dJqQLQ==,type:str]
    namespace: ENC[AES256_GCM,data:8LIW,iv:W8YA6B3aRvEwgtzRZb7PFE7NFyRdq1uLS+Z2We1h0xE=,tag:5rHiuyD4t3EzPnXE7yXn6A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:dfbWNA9L4CdDAMRUem9GbQ==,iv:j856gDZk8ze/lBozmwTHinjYaK3dIiroIxV8xEuUDug=,tag:O9v8FNzp3woTUx6p3OrnMA==,type:str]
        app.kubernetes.io/env: ENC[AES256_GCM,data:sNrl,iv:aZERkmZlLZfq6zAAsFPHIIbrQhFJCs6oUyV8h/2RZe4=,tag:X1BhiUnHEHbWScftSYj1AQ==,type:str]
type: ENC[AES256_GCM,data:8gJ07VlF,iv:HajICeXPIeW+a4P6UU3J1yCYzHJp+SGnMNs3C+Szxg4=,tag:9oH46XR6Uk6eFTEz0dgVsw==,type:str]
stringData:
    #ENC[AES256_GCM,data:afBrrGj6dyUUhqsQ7/QdPm6b+Xp4WpfZ/LXMGV+52yBtLPqAWuMxYkNhp5r6UhtkTmEPLYr2pocGrabZuSPhZNq8acCMBsc8YOPuyy+duf1qL4GoU74+/eL3IQYwBJu7CkAR3mjQFli7foJ81uU1wibPykNqBIq2Ix8F+1rkFQGL/rBFcXyf7WHtXPg+jrPJh3B1O84YdtgpQF8=,iv:4wl3aAy46w/YvZSI9CI1d/NHj9mJUGWE0/GkoJ4FmwA=,tag:7rLAXqpf611l5Urz/oAoHQ==,type:comment]
    #ENC[AES256_GCM,data:HtWA7nTg05VSI1oRccVd1sq7aI/F9V9kLKZGthqheCH1ciU/CMCe9ruFgZreaUz1In7ZbgEvMMvwZXU=,iv:OgjVo2HdGXhuApgrzInLy+hFin8BJ0h4kTOw5BPxhyg=,tag:GTh5rk/8IodXM+oWSPJBBA==,type:comment]
    #ENC[AES256_GCM,data:eDaEuUpnDHC/Ak5W8Yqtw6muN/hMJwtf/bP/5E2kMFB6f04lByRDR6zsaBNvWjHl5DpCDXgSCyo8t564L+D2fe+RVt206xWhXtUgVg==,iv:vv1lZ4lF494fJuOQDg/lx+ahF2aU03U9izx+JXjXwI8=,tag:UnqBanqeP2NKweDtd7IHkQ==,type:comment]
    #ENC[AES256_GCM,data:Z8Jk4s+Dp4bF3OtdvcSZNlt83uqWUtavobK7lzsxKXacRioY,iv:aCp5ve6rP0KUoVADBMqvagQEPPv9CPrgsdMuro6Ru5I=,tag:koSW2rY2X9dWe1nngI6Hlg==,type:comment]
    PROJECTOR_DATABASE_URL: ENC[AES256_GCM,data:h+6+AEQqRShJo0GPpqVrL0K+Mifv,iv:Ff9Yj/8rFcmB548uz38EXE8z1R629tbJpsvOZ/UB5k4=,tag:umHla/qY5vXgDEFqnorTpg==,type:str]
    #ENC[AES256_GCM,data:qxPwfgJ817dUQeI24dcnPuBGohpAhLUk8XCBMYVR1ol3yKtLu1+9da13zEpEoGNEK0P5cB1pNw==,iv:R3V1uUP+6w/KLnSu4yN5leJ+7PV1pTX5+j4IloKtyWs=,tag:6sptXPhWtCuTUqE61uGJIw==,type:comment]
sops:
    age:
        - recipient: age1p5v7s6gpq7grkdgldlguha9x3z79lgwl8vhwppwjs0xvng2g84rs8j67pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS1E3cWlaNlFDUXBNb0xy
            WWJSNkIrUlBtTDA3SjBqNGcxVDFSdklYZ0VjCkRVSS8wRGRHTEwvdmQrSmpWSjhD
            MHZyM3J6RlBPUGR2dVVSYUlDTkthRlEKLS0tICtscTZkdGN3UHU5R0tic2xjL1FE
            UUhpb2NmUGZTU2t0L1M1WVpFQWdBeXMKVkLahqQWT0Cefpp3ua4DQ6Ma1aDKCAlS
            L57ezPFsXX+6m/gLXAgKpXDwvwfckUp3wymMhVKdHmPKTb48X/ZOfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T06:45:29Z"
    mac: ENC[AES256_GCM,data:fD9Am2lCwx+JrTjb5IjfadDA01lGYsW+gi4AanSrwyGV+hDIQqTmuGanjVKZ5VZTqA1AlOYL0yC3OXePFicK7cW6ViXyHS3ST55ua5UV76J8rqvxaLdOl5Mcd7rNLo2GWpqNKrRJGF6VxO/P1IjyOoyNh7UWFdnonnktEDrtptA=,iv:yhY/iAOgr7TStjjsswJFyMIwO0Ns+gDiUCuqwXFCYkM=,tag:hOPim1/cJxZ4OjlpXMQxRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
